apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: devsamrood/orders
          imagePullPolicy: Never
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name # name of the pod running this service will be client id
            - name: MONGO_URI
              value: "mongodb://orders-mongo-srv:27017/orders"
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: "ticketing"
            - name: ORDER_EXPIRATION_MINUTES
              value: "15"
            - name: JWT_KEY # What will show up in code, can be different from the secret's key
              valueFrom:
                secretKeyRef:
                  name: jwt-secret # Name of the secret
                  key: JWT_KEY # The key from the secret's key value pair
---
apiVersion: v1
kind: Service
metadata:
  name: orders-srv
spec:
  type: ClusterIP
  selector:
    app: orders
  ports:
    - name: orders
      protocol: TCP
      port: 3000
      targetPort: 3000
